/*FICHERO PARA CREAR LAS TABLAS TEMPORALES*/

/*CREACION TABLA OCUPACION OFERTA*/                                 

DROP TABLE IF EXISTS OCUPACION_OFERTA;
CREATE TABLE OCUPACION_OFERTA(
    CURSO_ACADEMICO SMALLINT NOT NULL,
    ESTUDIO VARCHAR(200) NOT NULL,
    LOCALIDAD VARCHAR(200)NOT NULL,
    CENTRO VARCHAR(200) NOT NULL,
    TIPO_CENTRO VARCHAR(100),
    TIPO_ESTUDIO VARCHAR(50),
    PLAZAS_OFERTADAS SMALLINT,
    PLAZAS_MATRICULADAS SMALLINT,
    PLAZAS_SOLICITADAS SMALLINT,
    INDICE_OCUPACION FLOAT,
    FECHA_ACTUALIZACION DATE
);

/*-----------------------------------------------------------------------*/
/* CREACION TABLA RESULTADOS TITULACIONES */                      

DROP TABLE IF EXISTS RESULTADO_TITULACION;
CREATE TABLE RESULTADO_TITULACION(
    CURSO_ACADEMICO SMALLINT NOT NULL,
    CENTRO VARCHAR(200) NOT NULL,
    ESTUDIO VARCHAR(200) NOT NULL,
    TIPO_ESTUDIO VARCHAR(100),
    ALUMNOS_MATRICULADOS SMALLINT,
    ALUMNOS_NUEVO_INGRESO SMALLINT,
    PLAZAS_OFERTADAS SMALLINT,
    ALUMNOS_GRADUADOS SMALLINT,
    ALUMNOS_ADAPTA_GRADO_MATRI SMALLINT,
    ALUMNOS_ADAPTA_GRADO_MATRI_NI SMALLINT,
    ALUMNOS_ADAPTA_GRADO_TITULADO SMALLINT,
    ALUMNOS_CON_RECONOCIMIENTO SMALLINT,
    ALUMNOS_MOVILIDAD_ENTRADA SMALLINT,
    ALUMNOS_MOVILIDAD_SALIDA SMALLINT,
    CREDITOS_MATRICULADOS FLOAT,
    CREDITOS_RECONOCIDOS FLOAT,
    DURACION_MEDIA_GRADUADOS FLOAT,
    TASA_EXITO FLOAT,
    TASA_RENDIMIENTO FLOAT,
    TASA_EFICIENCIA FLOAT,
    TASA_ABANDONO FLOAT,
    TASA_GRADUACION FLOAT,
    FECHA_ACTUALIZACION DATE
);

/*-----------------------------------------------------------------------*/
/*CREACION TABLA NOTAS CORTE*/                                  

DROP TABLE IF EXISTS NOTA_CORTE;
CREATE TABLE NOTA_CORTE (
    CURSO_ACADEMICO SMALLINT NOT NULL,
    ESTUDIO VARCHAR(200) NOT NULL,
    LOCALIDAD VARCHAR(200)NOT NULL,
    CENTRO VARCHAR(200),
    PRELA_CONVO_NOTA_DEF FLOAT,
    NOTA_CORTE_DEFINITIVA_JULIO FLOAT,
    NOTA_CORTE_DEFINITIVA_SEPTIEMBRE FLOAT,
    FECHA_ACTUALIZACION DATE
);

/*-----------------------------------------------------------------------*/
/*CREACION TABLA ACUERDOS MOVILIDAD*/                             

DROP TABLE IF EXISTS ACUERDO_MOVILIDAD;
CREATE TABLE ACUERDO_MOVILIDAD(
    CURSO_ACADEMICO SMALLINT NOT NULL,
    NOMBRE_PROGRAMA_MOVILIDAD VARCHAR(50) NOT NULL,
    NOMBRE_AREA_ESTUDIOS_MOV VARCHAR(200) NOT NULL,
    CENTRO VARCHAR(200) NOT NULL,
    IN_OUT VARCHAR(4) NOT NULL,
    NOMBRE_IDIOMA_NIVEL_MOVILIDAD VARCHAR(100),
    PAIS_UNIVERSIDAD_ACUERDO VARCHAR(100),
    UNIVERSIDAD_ACUERDO VARCHAR(200),
    PLAZAS_OFERTADAS_ALUMNOS SMALLINT,
    PLAZAS_ASIGNADAS_ALUMNOS_OUT SMALLINT,
    FECHA_ACTUALIZACION DATE
);


/*-----------------------------------------------------------------------*/
/*CREACION TABLA ALUMNOS EGRESADOS*/

DROP TABLE IF EXISTS ALUMNO_EGRESADO;
CREATE TABLE ALUMNO_EGRESADO(
    CURSO_ACADEMICO SMALLINT NOT NULL,
    LOCALIDAD VARCHAR(200)NOT NULL,
    ESTUDIO VARCHAR(200) NOT NULL,
    TIPO_ESTUDIO VARCHAR(200),
    TIPO_EGRESO VARCHAR(200),
    SEXO VARCHAR(50),
    ALUMNOS_GRADUADOS SMALLINT,
    ALUMNOS_INTERRUMPEN_ESTUDIOS SMALLINT,
    ALUMNOS_INTERRUMPEN_EST_ANO1 SMALLINT,
    ALUMNOS_TRASLADAN_OTRA_UNIV SMALLINT,
    DURACION_MEDIA_GRADUADOS FLOAT,
    TASA_EFICIENCIA FLOAT,
    FECHA_ACTUALIZACION DATE
);

/*-----------------------------------------------------------------------*/
/*CREACION TABLA RENDIMIENTO POR ASIGNATURA Y TITULACIÓN*/               

DROP TABLE IF EXISTS RENDIMIENTO_ASIGNATURA_TITULACION;
CREATE TABLE RENDIMIENTO_ASIGNATURA_TITULACION(
    CURSO_ACADEMICO SMALLINT NOT NULL,
    TIPO_ESTUDIO VARCHAR(200) NOT NULL,
    ESTUDIO VARCHAR(200) NOT NULL,
    LOCALIDAD VARCHAR(200)NOT NULL,
    CENTRO VARCHAR(200) NOT NULL,
    ASIGNATURA VARCHAR(200),
    TIPO_ASIGNATURA VARCHAR(200),
    CLASE_ASIGNATURA VARCHAR(50),
    TASA_EXITO FLOAT,
    TASA_RENDIMIENTO FLOAT,
    TASA_EVALUACION FLOAT,
    ALUMNOS_EVALUADOS SMALLINT,
    ALUMNOS_SUPERADOS SMALLINT,
    ALUMNOS_PRESENTADOS SMALLINT,
    MEDIA_CONVOCATORIAS_CONSUMIDAS FLOAT,
    FECHA_ACTUALIZACION DATE
);
