/*Nos conectamos a la base de datos*/
use practica1_780336;

DROP TABLE IF EXISTS OCUPACION_OFERTA;
DROP TABLE IF EXISTS RESULTADO_TITULACION;
DROP TABLE IF EXISTS NOTA_CORTE;
DROP TABLE IF EXISTS ACUERDO_MOVILIDAD;
DROP TABLE IF EXISTS ALUMNO_EGRESADO;
DROP TABLE IF EXISTS RENDIMIENTO_ASIGNATURA_TITULACION;